let header = document.querySelector('header')
let h1 = document.createElement('h1')
let texto = document.createTextNode("Techwear")
let main = document.querySelector('main')
let div1 = document.createElement('div')
let div2 = document.createElement('div')
let h2_1 = document.createElement('h2')
let h2_2 = document.createElement('h2')
let p1 = document.createElement('p')
let p2 = document.createElement('p')
let tituloh2_1 = document.createTextNode("O que é?")
let tituloh2_2 = document.createTextNode("Origem")
let textop1 = document.createTextNode("Techwear é um estilo que tem como foco a tecnologia nas peças de roupa e traz um aspecto futurista. Bem como aqueles filmes que retratam um mundo com a tecnologia bem avançada e os personagens se vestem todos de preto para se protegerem dos danos causados ao meio ambiente, sabe?")
let textop2 = document.createTextNode("O techwear se originou nas grandes metrópoles orientais, onde o inverno é bem rigoroso e há muitas indústrias. Por isso, as roupas deste estilo tem como principais características serem funcionais e quentes. Isso explica a quantidade de bolsos presentes no visual e a qualidade da roupa.")
let div3 = document.createElement('div')
let h2_3 = document.createElement('h2')
let p3 = document.createElement('p')
let tituloh2_3 = document.createTextNode("Como se vestir assim?")
let textop3 = document.createTextNode("Para ser um techwear, é necessário que voce tenha várias peças de cores neutras, PRINCIPALMENTE o preto. Ele é indispensável neste estilo. Além disso, é importante ressaltar novamente que foram feitas para serem úteis e quentes, para suportar o inverno rigoroso que está presente nos países nos quais o techwear se originou. As camadas de roupa são compstas de diversos bolsos, cintas, correntes, chapéus, máscaras e vários outros acessórios.")


header.appendChild(h1)
h1.appendChild(texto)
main.appendChild(div1)
main.appendChild(div2)
main.appendChild(div3)
div1.appendChild(h2_1)
div2.appendChild(h2_2)
div3.appendChild(h2_3)
h2_1.appendChild(tituloh2_1)
h2_2.appendChild(tituloh2_2)
h2_3.appendChild(tituloh2_3)
div1.appendChild(p1)
div2.appendChild(p2)
div3.appendChild(p3)
p1.appendChild(textop1)
p2.appendChild(textop2)
p3.appendChild(textop3)
